// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/gin-gonic/gin"
	"github.com/laudryfadian/starter-golang/internal/config"
	"github.com/laudryfadian/starter-golang/internal/handler"
	"github.com/laudryfadian/starter-golang/internal/middleware"
	"github.com/laudryfadian/starter-golang/internal/repository"
	"github.com/laudryfadian/starter-golang/internal/routes"
	"github.com/laudryfadian/starter-golang/internal/usecase"
)

// Injectors from injector.go:

func InitializeServer() (*gin.Engine, error) {
	database := config.ConnectDB()
	userRepository := repository.NewUserRepository(database)
	userUsecase := usecase.NewUserUsecase(userRepository)
	userHandler := handler.NewUserHandler(userUsecase)
	authMiddleware := middleware.NewAuthMiddleware(userRepository)
	engine := routes.SetupRoutes(userHandler, authMiddleware)
	return engine, nil
}
